### PR TITLE
fix: node modules components

### LINKED ISSUE #37: Issue with components from node_modules
It seems that vue-component-meta could not load components from node_modules.

Can be reproduced in [this branch](https://github.com/nuxtlabs/nuxt-component-meta/tree/external-components)

Screenshot 2022-08-29 at 13 53 58

/cc @stafyniaksacha

### PR DESCRIPTION
**Pull request by stafyniaksacha**
This PR includes components dir to generated `tsconfig` used to parse component meta.  
If we include all `node_modules`, the app start time is really affected.

We can add `node_modules/nuxt/dist/app/components` so native nuxt components will be typed too.

Modules which register components dirs should become before this module

Close #37

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -43,14 +44,20 @@ export default defineNuxtModule<ModuleOptions>({
       'export { components as default,  components }'
     ]
 
+    nuxt.hook('components:dirs', (dirs) => {
+      componentDirs = dirs
```
Comment (farnabaz) [inline src/module.ts:48]:
```suggestion
      componentDirs = [
        ...dirs,
        { path: resolveModule('nuxt').replace('/index.mjs', '/app') },
        { path: resolveModule('@nuxt/ui-templates').replace('/index.mjs', '/templates') }
      ]
```

This will add `nuxt` and `@nuxt/ui-templates` dirs

File: playground/nuxt.config.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
 import { defineNuxtConfig } from 'nuxt'
-import nuxtMetaModule from '../src/module'
+import nuxtMetaModule from 'nuxt-component-meta'
```
Comment (farnabaz) [inline playground/nuxt.config.ts:2]: By using the package, the playground will not use current changes in development mode and it will use the latest release.

As I checked, your fix works perfectly fine without adding dependencies to the playground and changing `dev:prepare` script

**Comment by stafyniaksacha** [comment]
@farnabaz should be done ;)

**Review by farnabaz — APPROVED** [review]
Thanks ❤️
